
#download the nginx image
FROM nginx:latest

#remove the default configuration = /usr/local/etc/nginx
#/usr/local/bin/nginx

#RUN rm /usr/local/bin/nginx/nginx.conf
#usr/local/etc/nginx/nginx.conf
##add our configuration
COPY nginx.conf /usr/local/bin/nginx/